### Create a new Post
POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

{
  "content": "This is my first post!",
  "userCreatorID": "507f1f77bcf86cd799439011"
}

### Create a new Comment
POST http://localhost:3000/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

{
  "description": "This is my first comment",
  "relatedPostID": "696ab875230554348fa5d7b2",
  "userCreatorID": "507f1f77bcf86cd799439011"
}

### Delete a Comment
DELETE http://localhost:3000/comment/695af0640fa0cdd3e306ad2c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Update an existing Post
PUT http://localhost:3000/post/696ab875230554348fa5d7b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

{
  "content": "This is my updated second post!",
  "userCreatorID": "507f1f77bcf86cd799439011"
}

### Delete an existing Post
DELETE  http://localhost:3000/post/696ab875230554348fa5d7b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Update an existing Comment
PUT http://localhost:3000/comment/695af0640fa0cdd3e306ad2c?relatedPostID=696ab875230554348fa5d7b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

{
  "description": "Thiss is my updated first comment",
  "userCreatorID": "507f1f77bcf86cd799439011",
  "relatedPostID": "696ab875230554348fa5d7b2"
}

### Get all Posts
GET http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU5MGZlYTg5NzRmZDZiMzYxNDcwODQiLCJyYW5kb20iOiIwLjQxNTM3NDQzMzM0OTk5MzgiLCJpYXQiOjE3Njk1NDMwOTIsImV4cCI6MTc2OTU0NjY5Mn0.NihUGyK8UsfAf82Js0wbfA1ka-A4hycoR7GgY7zPtyI

### Get a Post by ID
GET http://localhost:3000/post/696ab875230554348fa5d7b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Get all Comments
GET http://localhost:3000/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Get a Comment by ID
GET http://localhost:3000/comment/695af0640fa0cdd3e306ad2c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Get all Comments by relatedPostID
GET http://localhost:3000/comment?relatedPostID=696ab875230554348fa5d7b2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Get all Posts by userCreatorID
GET http://localhost:3000/post?userCreatorID=507f1f77bcf86cd799439011
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU5MGZlYTg5NzRmZDZiMzYxNDcwODQiLCJyYW5kb20iOiIwLjkzNDY0OTM1ODYxMTM3NjUiLCJpYXQiOjE3NjkyMDg2ODQsImV4cCI6MTc2OTIxMjI4NH0.789qTfr2qiR4OCYS0NZ4paMVJdC0cxgrwkMPxE-_-ME

### Create a new User
POST http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

{
  "username": "liam",
  "email": "liam1@example.com",
  "profileImage": "http://example.com/images/liam.jpg",
  "password": "securepassword123"
}

### Get a User by ID
GET http://localhost:3000/user/69590fd18974fd6b3614707f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Get all Users
GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Delete a User
DELETE http://localhost:3000/user/69590fd18974fd6b3614707f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

### Update an existing User
PUT http://localhost:3000/user/69590fd18974fd6b3614707f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZhYjdhMDIzMDU1NDM0OGZhNWQ3YTUiLCJyYW5kb20iOiIwLjI3MDE0OTQ5ODczNDI3OTg1IiwiaWF0IjoxNzY4NjAxNTA0LCJleHAiOjE3Njg2MDUxMDR9.fzbh-6Q-nYd7wu7Ou2dFupjxEViyYg2gcovzm1AKyzs

{
  "username": "liamhemo_updated",
  "email": "liamhemo_updated@example.com",
  "profileImage": "http://example.com/images/liam_updated.jpg",
  "password": "newsecurepassword456"
}

### User Registration
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
  "username": "annaeden",
  "email": "annaeden111@example.com",
  "profileImage": "http://example.com/images/liam_updated.jpg",
  "password": "mypassword"
}


### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "annaeden",
  "email": "annaeden@example.com",
  "profileImage": "http://example.com/images/liam_updated.jpg",
  "password": "mypassword"
}

### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTU5MGZlYTg5NzRmZDZiMzYxNDcwODQiLCJyYW5kb20iOiIwLjc4NTE0NTM2NDIyMjU0MTciLCJpYXQiOjE3Njg2MDE5OTksImV4cCI6MTc2ODY4ODM5OX0.CMdEePytD7DGAVjPXoHBIFgtB586Kn2_f8gasytLdCA"
} 

### User Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTU5MGZlYTg5NzRmZDZiMzYxNDcwODQiLCJyYW5kb20iOiIwLjc4NTE0NTM2NDIyMjU0MTciLCJpYXQiOjE3Njg2MDE5OTksImV4cCI6MTc2ODY4ODM5OX0.CMdEePytD7DGAVjPXoHBIFgtB586Kn2_f8gasytLdCA"
}

### Toggle Like on a Post
POST http://localhost:3000/post/handle-like/69590fb18974fd6b3614707c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU5MGZlYTg5NzRmZDZiMzYxNDcwODQiLCJyYW5kb20iOiIwLjQyMDQ3MDA1MjEzMTU0Njg3IiwiaWF0IjoxNzY5NTQzOTM4LCJleHAiOjE3Njk1NDc1Mzh9.BoLRi9uZB8ArVUXqaABbHJPltWNWcxUBqmG-cIi5AzA

{
  "userId": "69590fea8974fd6b36147084"
}
